fn p1() {
    // If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
    // Find the sum of all the multiples of 3 or 5 below 1000.

    let mut sum = 0;
    for i in 0..1000 {
        if i % 5 == 0 || i % 3 == 0 {
            sum += i
        } 
    }
    println!("A1: {}", sum);
}


fn p2() {
    // Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    //
    let mut prev_prev = 1;
    let mut prev = 2;
    let mut sum = 2;
    while prev < 4000000 {
        let tmp = prev;
        prev = prev_prev + prev;
        prev_prev = tmp;
        if prev % 2 == 0 {
            sum += prev
        }
    }
    println!("A2: {}", sum);

}
fn main() {
    //println!("Hello, world!");
    p1();
    p2();
}
